platform :ios, '11.0'

workspace 'app.xcworkspace'

target 'SEPA Debit Example (Swift)' do
  project 'SEPA Debit Example (Swift).xcodeproj'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample
  pod 'Stripe'
end

target 'SEPA Debit Example (ObjC)' do
  project 'SEPA Debit Example (ObjC).xcodeproj'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample
  pod 'Stripe'
end

